### ISSUE TITLE
Copy files with history

### ISSUE THREAD

**Issue by Pascal666** [lxc/lxc-templates#2]
Because of the way this repository was created, all file history was lost.

Please delete this repository and re-create it, copying the files in such a way as to preserve their history.  Instructions on how to do this can be found many places.  Google works well for this kind of thing: https://www.google.com/search?q=github+one+repo+to+another+preserving+history

Thank you.

**Comment by cvoges12** [comment]
I think if we followed [this](https://medium.com/@ayushya/move-directory-from-one-repository-to-another-preserving-git-history-d210fa049d4b) then we could preserve the github repo while modifying to preserve history.

**Comment by stgraber** [comment]
Well, we could have done things differently at the time this got split up from LXC but then that would have also carried over a decade of unrelated git refs which isn't exactly ideal. The LXC repo still exists so should someone need to go look up the history, it's quite easy to do.
