### ISSUE TITLE
Why deprecated?

### ISSUE THREAD

**Issue by andreasbaumann** [lxc/lxc-templates#22]
I quite liked your shell scripts.

distrobuilder is a big Go monster, the format is yaml (why should shell commands
be written as yaml?). I cannot find an equally big collection of supported Linux
distributions. I like to build locally against local caches of linux distros. etc.

Are you still accepting fixes and pull requests?

Any plans to keep this lxc-templates project maybe alive as is..

**Comment by andreasbaumann** [comment]
Ah, I see my questions are answered here:

https://brauner.github.io/2018/02/27/lxc-removes-legacy-template-build-system.html

**Comment by cvoges12** [comment]
@stgraber Can we close this issue then?

**Comment by andreasbaumann** [comment]
Sure, go ahead. :-)
